version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "github-actions"
    target-branch: "development"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    assignees:
      - "XNonymous-N2"
      
  - package-ecosystem: "gradle"
    target-branch: "development"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "XNonymous-N2"
